/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Set;

/**
 * BTCompanySummaryInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTCompanySummaryInfo {
  public static final String SERIALIZED_NAME_ADMIN = "admin";
  @SerializedName(SERIALIZED_NAME_ADMIN)
  private Boolean admin;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DOMAIN_PREFIX = "domainPrefix";
  @SerializedName(SERIALIZED_NAME_DOMAIN_PREFIX)
  private String domainPrefix;

  public static final String SERIALIZED_NAME_ENTERPRISE_BASE_URL = "enterpriseBaseUrl";
  @SerializedName(SERIALIZED_NAME_ENTERPRISE_BASE_URL)
  private String enterpriseBaseUrl;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NO_PUBLIC_DOCUMENTS = "noPublicDocuments";
  @SerializedName(SERIALIZED_NAME_NO_PUBLIC_DOCUMENTS)
  private Boolean noPublicDocuments;

  public static final String SERIALIZED_NAME_OWNER_ID = "ownerId";
  @SerializedName(SERIALIZED_NAME_OWNER_ID)
  private String ownerId;

  public static final String SERIALIZED_NAME_SECONDARY_DOMAIN_PREFIXES = "secondaryDomainPrefixes";
  @SerializedName(SERIALIZED_NAME_SECONDARY_DOMAIN_PREFIXES)
  private Set<String> secondaryDomainPrefixes = null;

  public static final String SERIALIZED_NAME_STATE = "state";
  @SerializedName(SERIALIZED_NAME_STATE)
  private Integer state;

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private Integer type;

  public static final String SERIALIZED_NAME_VIEW_REF = "viewRef";
  @SerializedName(SERIALIZED_NAME_VIEW_REF)
  private URI viewRef;

  public BTCompanySummaryInfo() { 
  }

  public BTCompanySummaryInfo admin(Boolean admin) {
    
    this.admin = admin;
    return this;
  }

   /**
   * Get admin
   * @return admin
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAdmin() {
    return admin;
  }


  public void setAdmin(Boolean admin) {
    this.admin = admin;
  }


  public BTCompanySummaryInfo description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public BTCompanySummaryInfo domainPrefix(String domainPrefix) {
    
    this.domainPrefix = domainPrefix;
    return this;
  }

   /**
   * Get domainPrefix
   * @return domainPrefix
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDomainPrefix() {
    return domainPrefix;
  }


  public void setDomainPrefix(String domainPrefix) {
    this.domainPrefix = domainPrefix;
  }


  public BTCompanySummaryInfo enterpriseBaseUrl(String enterpriseBaseUrl) {
    
    this.enterpriseBaseUrl = enterpriseBaseUrl;
    return this;
  }

   /**
   * Get enterpriseBaseUrl
   * @return enterpriseBaseUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEnterpriseBaseUrl() {
    return enterpriseBaseUrl;
  }


  public void setEnterpriseBaseUrl(String enterpriseBaseUrl) {
    this.enterpriseBaseUrl = enterpriseBaseUrl;
  }


  public BTCompanySummaryInfo href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public BTCompanySummaryInfo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BTCompanySummaryInfo image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public BTCompanySummaryInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public BTCompanySummaryInfo noPublicDocuments(Boolean noPublicDocuments) {
    
    this.noPublicDocuments = noPublicDocuments;
    return this;
  }

   /**
   * Get noPublicDocuments
   * @return noPublicDocuments
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getNoPublicDocuments() {
    return noPublicDocuments;
  }


  public void setNoPublicDocuments(Boolean noPublicDocuments) {
    this.noPublicDocuments = noPublicDocuments;
  }


  public BTCompanySummaryInfo ownerId(String ownerId) {
    
    this.ownerId = ownerId;
    return this;
  }

   /**
   * Get ownerId
   * @return ownerId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOwnerId() {
    return ownerId;
  }


  public void setOwnerId(String ownerId) {
    this.ownerId = ownerId;
  }


  public BTCompanySummaryInfo secondaryDomainPrefixes(Set<String> secondaryDomainPrefixes) {
    
    this.secondaryDomainPrefixes = secondaryDomainPrefixes;
    return this;
  }

  public BTCompanySummaryInfo addSecondaryDomainPrefixesItem(String secondaryDomainPrefixesItem) {
    if (this.secondaryDomainPrefixes == null) {
      this.secondaryDomainPrefixes = new LinkedHashSet<String>();
    }
    this.secondaryDomainPrefixes.add(secondaryDomainPrefixesItem);
    return this;
  }

   /**
   * Get secondaryDomainPrefixes
   * @return secondaryDomainPrefixes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Set<String> getSecondaryDomainPrefixes() {
    return secondaryDomainPrefixes;
  }


  public void setSecondaryDomainPrefixes(Set<String> secondaryDomainPrefixes) {
    this.secondaryDomainPrefixes = secondaryDomainPrefixes;
  }


  public BTCompanySummaryInfo state(Integer state) {
    
    this.state = state;
    return this;
  }

   /**
   * Get state
   * @return state
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getState() {
    return state;
  }


  public void setState(Integer state) {
    this.state = state;
  }


  public BTCompanySummaryInfo type(Integer type) {
    
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getType() {
    return type;
  }


  public void setType(Integer type) {
    this.type = type;
  }


  public BTCompanySummaryInfo viewRef(URI viewRef) {
    
    this.viewRef = viewRef;
    return this;
  }

   /**
   * Get viewRef
   * @return viewRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getViewRef() {
    return viewRef;
  }


  public void setViewRef(URI viewRef) {
    this.viewRef = viewRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTCompanySummaryInfo btCompanySummaryInfo = (BTCompanySummaryInfo) o;
    return Objects.equals(this.admin, btCompanySummaryInfo.admin) &&
        Objects.equals(this.description, btCompanySummaryInfo.description) &&
        Objects.equals(this.domainPrefix, btCompanySummaryInfo.domainPrefix) &&
        Objects.equals(this.enterpriseBaseUrl, btCompanySummaryInfo.enterpriseBaseUrl) &&
        Objects.equals(this.href, btCompanySummaryInfo.href) &&
        Objects.equals(this.id, btCompanySummaryInfo.id) &&
        Objects.equals(this.image, btCompanySummaryInfo.image) &&
        Objects.equals(this.name, btCompanySummaryInfo.name) &&
        Objects.equals(this.noPublicDocuments, btCompanySummaryInfo.noPublicDocuments) &&
        Objects.equals(this.ownerId, btCompanySummaryInfo.ownerId) &&
        Objects.equals(this.secondaryDomainPrefixes, btCompanySummaryInfo.secondaryDomainPrefixes) &&
        Objects.equals(this.state, btCompanySummaryInfo.state) &&
        Objects.equals(this.type, btCompanySummaryInfo.type) &&
        Objects.equals(this.viewRef, btCompanySummaryInfo.viewRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(admin, description, domainPrefix, enterpriseBaseUrl, href, id, image, name, noPublicDocuments, ownerId, secondaryDomainPrefixes, state, type, viewRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTCompanySummaryInfo {\n");
    sb.append("    admin: ").append(toIndentedString(admin)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    domainPrefix: ").append(toIndentedString(domainPrefix)).append("\n");
    sb.append("    enterpriseBaseUrl: ").append(toIndentedString(enterpriseBaseUrl)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    noPublicDocuments: ").append(toIndentedString(noPublicDocuments)).append("\n");
    sb.append("    ownerId: ").append(toIndentedString(ownerId)).append("\n");
    sb.append("    secondaryDomainPrefixes: ").append(toIndentedString(secondaryDomainPrefixes)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    viewRef: ").append(toIndentedString(viewRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

