/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.openapitools.client.model.BTOwnerInfo;
import org.openapitools.client.model.BTUserBasicSummaryInfo;
import org.threeten.bp.OffsetDateTime;

/**
 * BTDocumentLabelInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTDocumentLabelInfo {
  public static final String SERIALIZED_NAME_CAN_MOVE = "canMove";
  @SerializedName(SERIALIZED_NAME_CAN_MOVE)
  private Boolean canMove;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private BTUserBasicSummaryInfo createdBy;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IS_CONTAINER = "isContainer";
  @SerializedName(SERIALIZED_NAME_IS_CONTAINER)
  private Boolean isContainer;

  public static final String SERIALIZED_NAME_IS_ENTERPRISE_OWNED = "isEnterpriseOwned";
  @SerializedName(SERIALIZED_NAME_IS_ENTERPRISE_OWNED)
  private Boolean isEnterpriseOwned;

  public static final String SERIALIZED_NAME_IS_MUTABLE = "isMutable";
  @SerializedName(SERIALIZED_NAME_IS_MUTABLE)
  private Boolean isMutable;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private BTUserBasicSummaryInfo modifiedBy;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private BTOwnerInfo owner;

  public static final String SERIALIZED_NAME_PARENT_LABEL_ID = "parentLabelId";
  @SerializedName(SERIALIZED_NAME_PARENT_LABEL_ID)
  private String parentLabelId;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  private String projectId;

  public static final String SERIALIZED_NAME_RESOURCE_TYPE = "resourceType";
  @SerializedName(SERIALIZED_NAME_RESOURCE_TYPE)
  private String resourceType;

  public static final String SERIALIZED_NAME_TREE_HREF = "treeHref";
  @SerializedName(SERIALIZED_NAME_TREE_HREF)
  private String treeHref;

  public static final String SERIALIZED_NAME_VIEW_REF = "viewRef";
  @SerializedName(SERIALIZED_NAME_VIEW_REF)
  private URI viewRef;

  public BTDocumentLabelInfo() { 
  }

  public BTDocumentLabelInfo canMove(Boolean canMove) {
    
    this.canMove = canMove;
    return this;
  }

   /**
   * Get canMove
   * @return canMove
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanMove() {
    return canMove;
  }


  public void setCanMove(Boolean canMove) {
    this.canMove = canMove;
  }


  public BTDocumentLabelInfo createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public BTDocumentLabelInfo createdBy(BTUserBasicSummaryInfo createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTUserBasicSummaryInfo getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(BTUserBasicSummaryInfo createdBy) {
    this.createdBy = createdBy;
  }


  public BTDocumentLabelInfo description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public BTDocumentLabelInfo href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public BTDocumentLabelInfo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BTDocumentLabelInfo isContainer(Boolean isContainer) {
    
    this.isContainer = isContainer;
    return this;
  }

   /**
   * Get isContainer
   * @return isContainer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsContainer() {
    return isContainer;
  }


  public void setIsContainer(Boolean isContainer) {
    this.isContainer = isContainer;
  }


  public BTDocumentLabelInfo isEnterpriseOwned(Boolean isEnterpriseOwned) {
    
    this.isEnterpriseOwned = isEnterpriseOwned;
    return this;
  }

   /**
   * Get isEnterpriseOwned
   * @return isEnterpriseOwned
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsEnterpriseOwned() {
    return isEnterpriseOwned;
  }


  public void setIsEnterpriseOwned(Boolean isEnterpriseOwned) {
    this.isEnterpriseOwned = isEnterpriseOwned;
  }


  public BTDocumentLabelInfo isMutable(Boolean isMutable) {
    
    this.isMutable = isMutable;
    return this;
  }

   /**
   * Get isMutable
   * @return isMutable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsMutable() {
    return isMutable;
  }


  public void setIsMutable(Boolean isMutable) {
    this.isMutable = isMutable;
  }


  public BTDocumentLabelInfo modifiedAt(OffsetDateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public BTDocumentLabelInfo modifiedBy(BTUserBasicSummaryInfo modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTUserBasicSummaryInfo getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(BTUserBasicSummaryInfo modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public BTDocumentLabelInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public BTDocumentLabelInfo owner(BTOwnerInfo owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTOwnerInfo getOwner() {
    return owner;
  }


  public void setOwner(BTOwnerInfo owner) {
    this.owner = owner;
  }


  public BTDocumentLabelInfo parentLabelId(String parentLabelId) {
    
    this.parentLabelId = parentLabelId;
    return this;
  }

   /**
   * Get parentLabelId
   * @return parentLabelId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParentLabelId() {
    return parentLabelId;
  }


  public void setParentLabelId(String parentLabelId) {
    this.parentLabelId = parentLabelId;
  }


  public BTDocumentLabelInfo path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public BTDocumentLabelInfo projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProjectId() {
    return projectId;
  }


  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public BTDocumentLabelInfo resourceType(String resourceType) {
    
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getResourceType() {
    return resourceType;
  }


  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }


  public BTDocumentLabelInfo treeHref(String treeHref) {
    
    this.treeHref = treeHref;
    return this;
  }

   /**
   * Get treeHref
   * @return treeHref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTreeHref() {
    return treeHref;
  }


  public void setTreeHref(String treeHref) {
    this.treeHref = treeHref;
  }


  public BTDocumentLabelInfo viewRef(URI viewRef) {
    
    this.viewRef = viewRef;
    return this;
  }

   /**
   * Get viewRef
   * @return viewRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getViewRef() {
    return viewRef;
  }


  public void setViewRef(URI viewRef) {
    this.viewRef = viewRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTDocumentLabelInfo btDocumentLabelInfo = (BTDocumentLabelInfo) o;
    return Objects.equals(this.canMove, btDocumentLabelInfo.canMove) &&
        Objects.equals(this.createdAt, btDocumentLabelInfo.createdAt) &&
        Objects.equals(this.createdBy, btDocumentLabelInfo.createdBy) &&
        Objects.equals(this.description, btDocumentLabelInfo.description) &&
        Objects.equals(this.href, btDocumentLabelInfo.href) &&
        Objects.equals(this.id, btDocumentLabelInfo.id) &&
        Objects.equals(this.isContainer, btDocumentLabelInfo.isContainer) &&
        Objects.equals(this.isEnterpriseOwned, btDocumentLabelInfo.isEnterpriseOwned) &&
        Objects.equals(this.isMutable, btDocumentLabelInfo.isMutable) &&
        Objects.equals(this.modifiedAt, btDocumentLabelInfo.modifiedAt) &&
        Objects.equals(this.modifiedBy, btDocumentLabelInfo.modifiedBy) &&
        Objects.equals(this.name, btDocumentLabelInfo.name) &&
        Objects.equals(this.owner, btDocumentLabelInfo.owner) &&
        Objects.equals(this.parentLabelId, btDocumentLabelInfo.parentLabelId) &&
        Objects.equals(this.path, btDocumentLabelInfo.path) &&
        Objects.equals(this.projectId, btDocumentLabelInfo.projectId) &&
        Objects.equals(this.resourceType, btDocumentLabelInfo.resourceType) &&
        Objects.equals(this.treeHref, btDocumentLabelInfo.treeHref) &&
        Objects.equals(this.viewRef, btDocumentLabelInfo.viewRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(canMove, createdAt, createdBy, description, href, id, isContainer, isEnterpriseOwned, isMutable, modifiedAt, modifiedBy, name, owner, parentLabelId, path, projectId, resourceType, treeHref, viewRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTDocumentLabelInfo {\n");
    sb.append("    canMove: ").append(toIndentedString(canMove)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isContainer: ").append(toIndentedString(isContainer)).append("\n");
    sb.append("    isEnterpriseOwned: ").append(toIndentedString(isEnterpriseOwned)).append("\n");
    sb.append("    isMutable: ").append(toIndentedString(isMutable)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    parentLabelId: ").append(toIndentedString(parentLabelId)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    treeHref: ").append(toIndentedString(treeHref)).append("\n");
    sb.append("    viewRef: ").append(toIndentedString(viewRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

