/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BTBaseInfo;
import org.openapitools.client.model.BTDocumentLabelInfo;
import org.openapitools.client.model.BTDocumentProcessingInfo;
import org.openapitools.client.model.BTOwnerInfo;
import org.openapitools.client.model.BTThumbnailInfo;
import org.openapitools.client.model.BTUserBasicSummaryInfo;
import org.openapitools.client.model.BTWorkspaceInfo;
import org.threeten.bp.OffsetDateTime;

/**
 * BTDocumentInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTDocumentInfo {
  public static final String SERIALIZED_NAME_ANONYMOUS_ACCESS_ALLOWED = "anonymousAccessAllowed";
  @SerializedName(SERIALIZED_NAME_ANONYMOUS_ACCESS_ALLOWED)
  private Boolean anonymousAccessAllowed;

  public static final String SERIALIZED_NAME_ANONYMOUS_ALLOWS_EXPORT = "anonymousAllowsExport";
  @SerializedName(SERIALIZED_NAME_ANONYMOUS_ALLOWS_EXPORT)
  private Boolean anonymousAllowsExport;

  public static final String SERIALIZED_NAME_BETA_CAPABILITY_IDS = "betaCapabilityIds";
  @SerializedName(SERIALIZED_NAME_BETA_CAPABILITY_IDS)
  private List<String> betaCapabilityIds = null;

  public static final String SERIALIZED_NAME_CAN_MOVE = "canMove";
  @SerializedName(SERIALIZED_NAME_CAN_MOVE)
  private Boolean canMove;

  public static final String SERIALIZED_NAME_CAN_UNSHARE = "canUnshare";
  @SerializedName(SERIALIZED_NAME_CAN_UNSHARE)
  private Boolean canUnshare;

  public static final String SERIALIZED_NAME_CREATED_AT = "createdAt";
  @SerializedName(SERIALIZED_NAME_CREATED_AT)
  private OffsetDateTime createdAt;

  public static final String SERIALIZED_NAME_CREATED_BY = "createdBy";
  @SerializedName(SERIALIZED_NAME_CREATED_BY)
  private BTUserBasicSummaryInfo createdBy;

  public static final String SERIALIZED_NAME_CREATED_WITH_EDUCATION_PLAN = "createdWithEducationPlan";
  @SerializedName(SERIALIZED_NAME_CREATED_WITH_EDUCATION_PLAN)
  private Boolean createdWithEducationPlan;

  public static final String SERIALIZED_NAME_DEFAULT_ELEMENT_ID = "defaultElementId";
  @SerializedName(SERIALIZED_NAME_DEFAULT_ELEMENT_ID)
  private String defaultElementId;

  public static final String SERIALIZED_NAME_DEFAULT_WORKSPACE = "defaultWorkspace";
  @SerializedName(SERIALIZED_NAME_DEFAULT_WORKSPACE)
  private BTWorkspaceInfo defaultWorkspace;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_DOCUMENT_LABELS = "documentLabels";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_LABELS)
  private List<BTDocumentLabelInfo> documentLabels = null;

  public static final String SERIALIZED_NAME_DOCUMENT_THUMBNAIL_ELEMENT_ID = "documentThumbnailElementId";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_THUMBNAIL_ELEMENT_ID)
  private String documentThumbnailElementId;

  public static final String SERIALIZED_NAME_DOCUMENT_TYPE = "documentType";
  @SerializedName(SERIALIZED_NAME_DOCUMENT_TYPE)
  private Integer documentType;

  public static final String SERIALIZED_NAME_DUPLICATE_NAME_VIOLATION_ERROR = "duplicateNameViolationError";
  @SerializedName(SERIALIZED_NAME_DUPLICATE_NAME_VIOLATION_ERROR)
  private String duplicateNameViolationError;

  public static final String SERIALIZED_NAME_HAS_RELEASE_REVISIONABLE_OBJECTS = "hasReleaseRevisionableObjects";
  @SerializedName(SERIALIZED_NAME_HAS_RELEASE_REVISIONABLE_OBJECTS)
  private Boolean hasReleaseRevisionableObjects;

  public static final String SERIALIZED_NAME_HAS_RELEVANT_INSERTABLES = "hasRelevantInsertables";
  @SerializedName(SERIALIZED_NAME_HAS_RELEVANT_INSERTABLES)
  private Boolean hasRelevantInsertables;

  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_IS_CONTAINER = "isContainer";
  @SerializedName(SERIALIZED_NAME_IS_CONTAINER)
  private Boolean isContainer;

  public static final String SERIALIZED_NAME_IS_ENTERPRISE_OWNED = "isEnterpriseOwned";
  @SerializedName(SERIALIZED_NAME_IS_ENTERPRISE_OWNED)
  private Boolean isEnterpriseOwned;

  public static final String SERIALIZED_NAME_IS_MUTABLE = "isMutable";
  @SerializedName(SERIALIZED_NAME_IS_MUTABLE)
  private Boolean isMutable;

  public static final String SERIALIZED_NAME_IS_ORPHANED = "isOrphaned";
  @SerializedName(SERIALIZED_NAME_IS_ORPHANED)
  private Boolean isOrphaned;

  public static final String SERIALIZED_NAME_IS_UPGRADED_TO_LATEST_VERSION = "isUpgradedToLatestVersion";
  @SerializedName(SERIALIZED_NAME_IS_UPGRADED_TO_LATEST_VERSION)
  private Boolean isUpgradedToLatestVersion;

  public static final String SERIALIZED_NAME_IS_USING_MANAGED_WORKFLOW = "isUsingManagedWorkflow";
  @SerializedName(SERIALIZED_NAME_IS_USING_MANAGED_WORKFLOW)
  private Boolean isUsingManagedWorkflow;

  public static final String SERIALIZED_NAME_LIKED_BY_CURRENT_USER = "likedByCurrentUser";
  @SerializedName(SERIALIZED_NAME_LIKED_BY_CURRENT_USER)
  private Boolean likedByCurrentUser;

  public static final String SERIALIZED_NAME_LIKES = "likes";
  @SerializedName(SERIALIZED_NAME_LIKES)
  private Long likes;

  public static final String SERIALIZED_NAME_MODIFIED_AT = "modifiedAt";
  @SerializedName(SERIALIZED_NAME_MODIFIED_AT)
  private OffsetDateTime modifiedAt;

  public static final String SERIALIZED_NAME_MODIFIED_BY = "modifiedBy";
  @SerializedName(SERIALIZED_NAME_MODIFIED_BY)
  private BTUserBasicSummaryInfo modifiedBy;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;

  public static final String SERIALIZED_NAME_NOT_REVISION_MANAGED = "notRevisionManaged";
  @SerializedName(SERIALIZED_NAME_NOT_REVISION_MANAGED)
  private Boolean notRevisionManaged;

  public static final String SERIALIZED_NAME_NUMBER_OF_TIMES_COPIED = "numberOfTimesCopied";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_TIMES_COPIED)
  private Long numberOfTimesCopied;

  public static final String SERIALIZED_NAME_NUMBER_OF_TIMES_REFERENCED = "numberOfTimesReferenced";
  @SerializedName(SERIALIZED_NAME_NUMBER_OF_TIMES_REFERENCED)
  private Long numberOfTimesReferenced;

  public static final String SERIALIZED_NAME_OWNER = "owner";
  @SerializedName(SERIALIZED_NAME_OWNER)
  private BTOwnerInfo owner;

  public static final String SERIALIZED_NAME_PARENT_ID = "parentId";
  @SerializedName(SERIALIZED_NAME_PARENT_ID)
  private String parentId;

  /**
   * Gets or Sets permission
   */
  @JsonAdapter(PermissionEnum.Adapter.class)
  public enum PermissionEnum {
    NOACCESS("NOACCESS"),
    
    ANONYMOUS_ACCESS("ANONYMOUS_ACCESS"),
    
    READ("READ"),
    
    READ_COPY_EXPORT("READ_COPY_EXPORT"),
    
    COMMENT("COMMENT"),
    
    WRITE("WRITE"),
    
    RESHARE("RESHARE"),
    
    FULL("FULL"),
    
    OWNER("OWNER");

    private String value;

    PermissionEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static PermissionEnum fromValue(String value) {
      for (PermissionEnum b : PermissionEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<PermissionEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final PermissionEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public PermissionEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return PermissionEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_PERMISSION = "permission";
  @SerializedName(SERIALIZED_NAME_PERMISSION)
  private PermissionEnum permission;

  public static final String SERIALIZED_NAME_PERMISSION_SET = "permissionSet";
  @SerializedName(SERIALIZED_NAME_PERMISSION_SET)
  private List<String> permissionSet = null;

  public static final String SERIALIZED_NAME_PROJECT_ID = "projectId";
  @SerializedName(SERIALIZED_NAME_PROJECT_ID)
  private String projectId;

  public static final String SERIALIZED_NAME_PUBLIC = "public";
  @SerializedName(SERIALIZED_NAME_PUBLIC)
  private Boolean _public;

  public static final String SERIALIZED_NAME_RECENT_VERSION = "recentVersion";
  @SerializedName(SERIALIZED_NAME_RECENT_VERSION)
  private BTBaseInfo recentVersion;

  public static final String SERIALIZED_NAME_RESOURCE_TYPE = "resourceType";
  @SerializedName(SERIALIZED_NAME_RESOURCE_TYPE)
  private String resourceType;

  public static final String SERIALIZED_NAME_SUPPORT_TEAM_USER_AND_SHARED = "supportTeamUserAndShared";
  @SerializedName(SERIALIZED_NAME_SUPPORT_TEAM_USER_AND_SHARED)
  private Boolean supportTeamUserAndShared;

  public static final String SERIALIZED_NAME_TAGS = "tags";
  @SerializedName(SERIALIZED_NAME_TAGS)
  private List<String> tags = null;

  public static final String SERIALIZED_NAME_THUMBNAIL = "thumbnail";
  @SerializedName(SERIALIZED_NAME_THUMBNAIL)
  private BTThumbnailInfo thumbnail;

  public static final String SERIALIZED_NAME_TOTAL_WORKSPACES_SCHEDULED_FOR_UPDATE = "totalWorkspacesScheduledForUpdate";
  @SerializedName(SERIALIZED_NAME_TOTAL_WORKSPACES_SCHEDULED_FOR_UPDATE)
  private Integer totalWorkspacesScheduledForUpdate;

  public static final String SERIALIZED_NAME_TOTAL_WORKSPACES_UPDATING = "totalWorkspacesUpdating";
  @SerializedName(SERIALIZED_NAME_TOTAL_WORKSPACES_UPDATING)
  private Integer totalWorkspacesUpdating;

  public static final String SERIALIZED_NAME_TRASH = "trash";
  @SerializedName(SERIALIZED_NAME_TRASH)
  private Boolean trash;

  public static final String SERIALIZED_NAME_TRASHED_AT = "trashedAt";
  @SerializedName(SERIALIZED_NAME_TRASHED_AT)
  private OffsetDateTime trashedAt;

  public static final String SERIALIZED_NAME_TREE_HREF = "treeHref";
  @SerializedName(SERIALIZED_NAME_TREE_HREF)
  private String treeHref;

  public static final String SERIALIZED_NAME_USER_ACCOUNT_LIMITS_BREACHED = "userAccountLimitsBreached";
  @SerializedName(SERIALIZED_NAME_USER_ACCOUNT_LIMITS_BREACHED)
  private Boolean userAccountLimitsBreached;

  public static final String SERIALIZED_NAME_VIEW_REF = "viewRef";
  @SerializedName(SERIALIZED_NAME_VIEW_REF)
  private URI viewRef;

  public BTDocumentInfo() { 
    this.jsonType = this.getClass().getSimpleName();
  }

  public BTDocumentInfo anonymousAccessAllowed(Boolean anonymousAccessAllowed) {
    
    this.anonymousAccessAllowed = anonymousAccessAllowed;
    return this;
  }

   /**
   * Get anonymousAccessAllowed
   * @return anonymousAccessAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAnonymousAccessAllowed() {
    return anonymousAccessAllowed;
  }


  public void setAnonymousAccessAllowed(Boolean anonymousAccessAllowed) {
    this.anonymousAccessAllowed = anonymousAccessAllowed;
  }


  public BTDocumentInfo anonymousAllowsExport(Boolean anonymousAllowsExport) {
    
    this.anonymousAllowsExport = anonymousAllowsExport;
    return this;
  }

   /**
   * Get anonymousAllowsExport
   * @return anonymousAllowsExport
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getAnonymousAllowsExport() {
    return anonymousAllowsExport;
  }


  public void setAnonymousAllowsExport(Boolean anonymousAllowsExport) {
    this.anonymousAllowsExport = anonymousAllowsExport;
  }


  public BTDocumentInfo betaCapabilityIds(List<String> betaCapabilityIds) {
    
    this.betaCapabilityIds = betaCapabilityIds;
    return this;
  }

  public BTDocumentInfo addBetaCapabilityIdsItem(String betaCapabilityIdsItem) {
    if (this.betaCapabilityIds == null) {
      this.betaCapabilityIds = new ArrayList<String>();
    }
    this.betaCapabilityIds.add(betaCapabilityIdsItem);
    return this;
  }

   /**
   * Get betaCapabilityIds
   * @return betaCapabilityIds
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getBetaCapabilityIds() {
    return betaCapabilityIds;
  }


  public void setBetaCapabilityIds(List<String> betaCapabilityIds) {
    this.betaCapabilityIds = betaCapabilityIds;
  }


  public BTDocumentInfo canMove(Boolean canMove) {
    
    this.canMove = canMove;
    return this;
  }

   /**
   * Get canMove
   * @return canMove
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanMove() {
    return canMove;
  }


  public void setCanMove(Boolean canMove) {
    this.canMove = canMove;
  }


  public BTDocumentInfo canUnshare(Boolean canUnshare) {
    
    this.canUnshare = canUnshare;
    return this;
  }

   /**
   * Get canUnshare
   * @return canUnshare
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCanUnshare() {
    return canUnshare;
  }


  public void setCanUnshare(Boolean canUnshare) {
    this.canUnshare = canUnshare;
  }


  public BTDocumentInfo createdAt(OffsetDateTime createdAt) {
    
    this.createdAt = createdAt;
    return this;
  }

   /**
   * Get createdAt
   * @return createdAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getCreatedAt() {
    return createdAt;
  }


  public void setCreatedAt(OffsetDateTime createdAt) {
    this.createdAt = createdAt;
  }


  public BTDocumentInfo createdBy(BTUserBasicSummaryInfo createdBy) {
    
    this.createdBy = createdBy;
    return this;
  }

   /**
   * Get createdBy
   * @return createdBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTUserBasicSummaryInfo getCreatedBy() {
    return createdBy;
  }


  public void setCreatedBy(BTUserBasicSummaryInfo createdBy) {
    this.createdBy = createdBy;
  }


  public BTDocumentInfo createdWithEducationPlan(Boolean createdWithEducationPlan) {
    
    this.createdWithEducationPlan = createdWithEducationPlan;
    return this;
  }

   /**
   * Get createdWithEducationPlan
   * @return createdWithEducationPlan
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getCreatedWithEducationPlan() {
    return createdWithEducationPlan;
  }


  public void setCreatedWithEducationPlan(Boolean createdWithEducationPlan) {
    this.createdWithEducationPlan = createdWithEducationPlan;
  }


  public BTDocumentInfo defaultElementId(String defaultElementId) {
    
    this.defaultElementId = defaultElementId;
    return this;
  }

   /**
   * Get defaultElementId
   * @return defaultElementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDefaultElementId() {
    return defaultElementId;
  }


  public void setDefaultElementId(String defaultElementId) {
    this.defaultElementId = defaultElementId;
  }


  public BTDocumentInfo defaultWorkspace(BTWorkspaceInfo defaultWorkspace) {
    
    this.defaultWorkspace = defaultWorkspace;
    return this;
  }

   /**
   * Get defaultWorkspace
   * @return defaultWorkspace
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTWorkspaceInfo getDefaultWorkspace() {
    return defaultWorkspace;
  }


  public void setDefaultWorkspace(BTWorkspaceInfo defaultWorkspace) {
    this.defaultWorkspace = defaultWorkspace;
  }


  public BTDocumentInfo description(String description) {
    
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public BTDocumentInfo documentLabels(List<BTDocumentLabelInfo> documentLabels) {
    
    this.documentLabels = documentLabels;
    return this;
  }

  public BTDocumentInfo addDocumentLabelsItem(BTDocumentLabelInfo documentLabelsItem) {
    if (this.documentLabels == null) {
      this.documentLabels = new ArrayList<BTDocumentLabelInfo>();
    }
    this.documentLabels.add(documentLabelsItem);
    return this;
  }

   /**
   * Get documentLabels
   * @return documentLabels
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BTDocumentLabelInfo> getDocumentLabels() {
    return documentLabels;
  }


  public void setDocumentLabels(List<BTDocumentLabelInfo> documentLabels) {
    this.documentLabels = documentLabels;
  }


  public BTDocumentInfo documentThumbnailElementId(String documentThumbnailElementId) {
    
    this.documentThumbnailElementId = documentThumbnailElementId;
    return this;
  }

   /**
   * Get documentThumbnailElementId
   * @return documentThumbnailElementId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDocumentThumbnailElementId() {
    return documentThumbnailElementId;
  }


  public void setDocumentThumbnailElementId(String documentThumbnailElementId) {
    this.documentThumbnailElementId = documentThumbnailElementId;
  }


  public BTDocumentInfo documentType(Integer documentType) {
    
    this.documentType = documentType;
    return this;
  }

   /**
   * Get documentType
   * @return documentType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getDocumentType() {
    return documentType;
  }


  public void setDocumentType(Integer documentType) {
    this.documentType = documentType;
  }


  public BTDocumentInfo duplicateNameViolationError(String duplicateNameViolationError) {
    
    this.duplicateNameViolationError = duplicateNameViolationError;
    return this;
  }

   /**
   * Get duplicateNameViolationError
   * @return duplicateNameViolationError
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDuplicateNameViolationError() {
    return duplicateNameViolationError;
  }


  public void setDuplicateNameViolationError(String duplicateNameViolationError) {
    this.duplicateNameViolationError = duplicateNameViolationError;
  }


  public BTDocumentInfo hasReleaseRevisionableObjects(Boolean hasReleaseRevisionableObjects) {
    
    this.hasReleaseRevisionableObjects = hasReleaseRevisionableObjects;
    return this;
  }

   /**
   * Get hasReleaseRevisionableObjects
   * @return hasReleaseRevisionableObjects
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasReleaseRevisionableObjects() {
    return hasReleaseRevisionableObjects;
  }


  public void setHasReleaseRevisionableObjects(Boolean hasReleaseRevisionableObjects) {
    this.hasReleaseRevisionableObjects = hasReleaseRevisionableObjects;
  }


  public BTDocumentInfo hasRelevantInsertables(Boolean hasRelevantInsertables) {
    
    this.hasRelevantInsertables = hasRelevantInsertables;
    return this;
  }

   /**
   * Get hasRelevantInsertables
   * @return hasRelevantInsertables
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getHasRelevantInsertables() {
    return hasRelevantInsertables;
  }


  public void setHasRelevantInsertables(Boolean hasRelevantInsertables) {
    this.hasRelevantInsertables = hasRelevantInsertables;
  }


  public BTDocumentInfo href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public BTDocumentInfo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BTDocumentInfo isContainer(Boolean isContainer) {
    
    this.isContainer = isContainer;
    return this;
  }

   /**
   * Get isContainer
   * @return isContainer
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsContainer() {
    return isContainer;
  }


  public void setIsContainer(Boolean isContainer) {
    this.isContainer = isContainer;
  }


  public BTDocumentInfo isEnterpriseOwned(Boolean isEnterpriseOwned) {
    
    this.isEnterpriseOwned = isEnterpriseOwned;
    return this;
  }

   /**
   * Get isEnterpriseOwned
   * @return isEnterpriseOwned
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsEnterpriseOwned() {
    return isEnterpriseOwned;
  }


  public void setIsEnterpriseOwned(Boolean isEnterpriseOwned) {
    this.isEnterpriseOwned = isEnterpriseOwned;
  }


  public BTDocumentInfo isMutable(Boolean isMutable) {
    
    this.isMutable = isMutable;
    return this;
  }

   /**
   * Get isMutable
   * @return isMutable
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsMutable() {
    return isMutable;
  }


  public void setIsMutable(Boolean isMutable) {
    this.isMutable = isMutable;
  }


  public BTDocumentInfo isOrphaned(Boolean isOrphaned) {
    
    this.isOrphaned = isOrphaned;
    return this;
  }

   /**
   * Get isOrphaned
   * @return isOrphaned
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsOrphaned() {
    return isOrphaned;
  }


  public void setIsOrphaned(Boolean isOrphaned) {
    this.isOrphaned = isOrphaned;
  }


  public BTDocumentInfo isUpgradedToLatestVersion(Boolean isUpgradedToLatestVersion) {
    
    this.isUpgradedToLatestVersion = isUpgradedToLatestVersion;
    return this;
  }

   /**
   * Get isUpgradedToLatestVersion
   * @return isUpgradedToLatestVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsUpgradedToLatestVersion() {
    return isUpgradedToLatestVersion;
  }


  public void setIsUpgradedToLatestVersion(Boolean isUpgradedToLatestVersion) {
    this.isUpgradedToLatestVersion = isUpgradedToLatestVersion;
  }


  public BTDocumentInfo isUsingManagedWorkflow(Boolean isUsingManagedWorkflow) {
    
    this.isUsingManagedWorkflow = isUsingManagedWorkflow;
    return this;
  }

   /**
   * Get isUsingManagedWorkflow
   * @return isUsingManagedWorkflow
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsUsingManagedWorkflow() {
    return isUsingManagedWorkflow;
  }


  public void setIsUsingManagedWorkflow(Boolean isUsingManagedWorkflow) {
    this.isUsingManagedWorkflow = isUsingManagedWorkflow;
  }


  public BTDocumentInfo likedByCurrentUser(Boolean likedByCurrentUser) {
    
    this.likedByCurrentUser = likedByCurrentUser;
    return this;
  }

   /**
   * Get likedByCurrentUser
   * @return likedByCurrentUser
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getLikedByCurrentUser() {
    return likedByCurrentUser;
  }


  public void setLikedByCurrentUser(Boolean likedByCurrentUser) {
    this.likedByCurrentUser = likedByCurrentUser;
  }


  public BTDocumentInfo likes(Long likes) {
    
    this.likes = likes;
    return this;
  }

   /**
   * Get likes
   * @return likes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getLikes() {
    return likes;
  }


  public void setLikes(Long likes) {
    this.likes = likes;
  }


  public BTDocumentInfo modifiedAt(OffsetDateTime modifiedAt) {
    
    this.modifiedAt = modifiedAt;
    return this;
  }

   /**
   * Get modifiedAt
   * @return modifiedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getModifiedAt() {
    return modifiedAt;
  }


  public void setModifiedAt(OffsetDateTime modifiedAt) {
    this.modifiedAt = modifiedAt;
  }


  public BTDocumentInfo modifiedBy(BTUserBasicSummaryInfo modifiedBy) {
    
    this.modifiedBy = modifiedBy;
    return this;
  }

   /**
   * Get modifiedBy
   * @return modifiedBy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTUserBasicSummaryInfo getModifiedBy() {
    return modifiedBy;
  }


  public void setModifiedBy(BTUserBasicSummaryInfo modifiedBy) {
    this.modifiedBy = modifiedBy;
  }


  public BTDocumentInfo name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  public BTDocumentInfo notRevisionManaged(Boolean notRevisionManaged) {
    
    this.notRevisionManaged = notRevisionManaged;
    return this;
  }

   /**
   * Get notRevisionManaged
   * @return notRevisionManaged
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getNotRevisionManaged() {
    return notRevisionManaged;
  }


  public void setNotRevisionManaged(Boolean notRevisionManaged) {
    this.notRevisionManaged = notRevisionManaged;
  }


  public BTDocumentInfo numberOfTimesCopied(Long numberOfTimesCopied) {
    
    this.numberOfTimesCopied = numberOfTimesCopied;
    return this;
  }

   /**
   * Get numberOfTimesCopied
   * @return numberOfTimesCopied
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getNumberOfTimesCopied() {
    return numberOfTimesCopied;
  }


  public void setNumberOfTimesCopied(Long numberOfTimesCopied) {
    this.numberOfTimesCopied = numberOfTimesCopied;
  }


  public BTDocumentInfo numberOfTimesReferenced(Long numberOfTimesReferenced) {
    
    this.numberOfTimesReferenced = numberOfTimesReferenced;
    return this;
  }

   /**
   * Get numberOfTimesReferenced
   * @return numberOfTimesReferenced
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Long getNumberOfTimesReferenced() {
    return numberOfTimesReferenced;
  }


  public void setNumberOfTimesReferenced(Long numberOfTimesReferenced) {
    this.numberOfTimesReferenced = numberOfTimesReferenced;
  }


  public BTDocumentInfo owner(BTOwnerInfo owner) {
    
    this.owner = owner;
    return this;
  }

   /**
   * Get owner
   * @return owner
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTOwnerInfo getOwner() {
    return owner;
  }


  public void setOwner(BTOwnerInfo owner) {
    this.owner = owner;
  }


  public BTDocumentInfo parentId(String parentId) {
    
    this.parentId = parentId;
    return this;
  }

   /**
   * Get parentId
   * @return parentId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getParentId() {
    return parentId;
  }


  public void setParentId(String parentId) {
    this.parentId = parentId;
  }


  public BTDocumentInfo permission(PermissionEnum permission) {
    
    this.permission = permission;
    return this;
  }

   /**
   * Get permission
   * @return permission
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public PermissionEnum getPermission() {
    return permission;
  }


  public void setPermission(PermissionEnum permission) {
    this.permission = permission;
  }


  public BTDocumentInfo permissionSet(List<String> permissionSet) {
    
    this.permissionSet = permissionSet;
    return this;
  }

  public BTDocumentInfo addPermissionSetItem(String permissionSetItem) {
    if (this.permissionSet == null) {
      this.permissionSet = new ArrayList<String>();
    }
    this.permissionSet.add(permissionSetItem);
    return this;
  }

   /**
   * Get permissionSet
   * @return permissionSet
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getPermissionSet() {
    return permissionSet;
  }


  public void setPermissionSet(List<String> permissionSet) {
    this.permissionSet = permissionSet;
  }


  public BTDocumentInfo projectId(String projectId) {
    
    this.projectId = projectId;
    return this;
  }

   /**
   * Get projectId
   * @return projectId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProjectId() {
    return projectId;
  }


  public void setProjectId(String projectId) {
    this.projectId = projectId;
  }


  public BTDocumentInfo _public(Boolean _public) {
    
    this._public = _public;
    return this;
  }

   /**
   * Get _public
   * @return _public
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPublic() {
    return _public;
  }


  public void setPublic(Boolean _public) {
    this._public = _public;
  }


  public BTDocumentInfo recentVersion(BTBaseInfo recentVersion) {
    
    this.recentVersion = recentVersion;
    return this;
  }

   /**
   * Get recentVersion
   * @return recentVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTBaseInfo getRecentVersion() {
    return recentVersion;
  }


  public void setRecentVersion(BTBaseInfo recentVersion) {
    this.recentVersion = recentVersion;
  }


  public BTDocumentInfo resourceType(String resourceType) {
    
    this.resourceType = resourceType;
    return this;
  }

   /**
   * Get resourceType
   * @return resourceType
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getResourceType() {
    return resourceType;
  }


  public void setResourceType(String resourceType) {
    this.resourceType = resourceType;
  }


  public BTDocumentInfo supportTeamUserAndShared(Boolean supportTeamUserAndShared) {
    
    this.supportTeamUserAndShared = supportTeamUserAndShared;
    return this;
  }

   /**
   * Get supportTeamUserAndShared
   * @return supportTeamUserAndShared
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getSupportTeamUserAndShared() {
    return supportTeamUserAndShared;
  }


  public void setSupportTeamUserAndShared(Boolean supportTeamUserAndShared) {
    this.supportTeamUserAndShared = supportTeamUserAndShared;
  }


  public BTDocumentInfo tags(List<String> tags) {
    
    this.tags = tags;
    return this;
  }

  public BTDocumentInfo addTagsItem(String tagsItem) {
    if (this.tags == null) {
      this.tags = new ArrayList<String>();
    }
    this.tags.add(tagsItem);
    return this;
  }

   /**
   * Get tags
   * @return tags
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getTags() {
    return tags;
  }


  public void setTags(List<String> tags) {
    this.tags = tags;
  }


  public BTDocumentInfo thumbnail(BTThumbnailInfo thumbnail) {
    
    this.thumbnail = thumbnail;
    return this;
  }

   /**
   * Get thumbnail
   * @return thumbnail
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTThumbnailInfo getThumbnail() {
    return thumbnail;
  }


  public void setThumbnail(BTThumbnailInfo thumbnail) {
    this.thumbnail = thumbnail;
  }


  public BTDocumentInfo totalWorkspacesScheduledForUpdate(Integer totalWorkspacesScheduledForUpdate) {
    
    this.totalWorkspacesScheduledForUpdate = totalWorkspacesScheduledForUpdate;
    return this;
  }

   /**
   * Get totalWorkspacesScheduledForUpdate
   * @return totalWorkspacesScheduledForUpdate
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalWorkspacesScheduledForUpdate() {
    return totalWorkspacesScheduledForUpdate;
  }


  public void setTotalWorkspacesScheduledForUpdate(Integer totalWorkspacesScheduledForUpdate) {
    this.totalWorkspacesScheduledForUpdate = totalWorkspacesScheduledForUpdate;
  }


  public BTDocumentInfo totalWorkspacesUpdating(Integer totalWorkspacesUpdating) {
    
    this.totalWorkspacesUpdating = totalWorkspacesUpdating;
    return this;
  }

   /**
   * Get totalWorkspacesUpdating
   * @return totalWorkspacesUpdating
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getTotalWorkspacesUpdating() {
    return totalWorkspacesUpdating;
  }


  public void setTotalWorkspacesUpdating(Integer totalWorkspacesUpdating) {
    this.totalWorkspacesUpdating = totalWorkspacesUpdating;
  }


  public BTDocumentInfo trash(Boolean trash) {
    
    this.trash = trash;
    return this;
  }

   /**
   * Get trash
   * @return trash
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTrash() {
    return trash;
  }


  public void setTrash(Boolean trash) {
    this.trash = trash;
  }


  public BTDocumentInfo trashedAt(OffsetDateTime trashedAt) {
    
    this.trashedAt = trashedAt;
    return this;
  }

   /**
   * Get trashedAt
   * @return trashedAt
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getTrashedAt() {
    return trashedAt;
  }


  public void setTrashedAt(OffsetDateTime trashedAt) {
    this.trashedAt = trashedAt;
  }


  public BTDocumentInfo treeHref(String treeHref) {
    
    this.treeHref = treeHref;
    return this;
  }

   /**
   * Get treeHref
   * @return treeHref
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTreeHref() {
    return treeHref;
  }


  public void setTreeHref(String treeHref) {
    this.treeHref = treeHref;
  }


  public BTDocumentInfo userAccountLimitsBreached(Boolean userAccountLimitsBreached) {
    
    this.userAccountLimitsBreached = userAccountLimitsBreached;
    return this;
  }

   /**
   * Get userAccountLimitsBreached
   * @return userAccountLimitsBreached
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getUserAccountLimitsBreached() {
    return userAccountLimitsBreached;
  }


  public void setUserAccountLimitsBreached(Boolean userAccountLimitsBreached) {
    this.userAccountLimitsBreached = userAccountLimitsBreached;
  }


  public BTDocumentInfo viewRef(URI viewRef) {
    
    this.viewRef = viewRef;
    return this;
  }

   /**
   * Get viewRef
   * @return viewRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getViewRef() {
    return viewRef;
  }


  public void setViewRef(URI viewRef) {
    this.viewRef = viewRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTDocumentInfo btDocumentInfo = (BTDocumentInfo) o;
    return Objects.equals(this.anonymousAccessAllowed, btDocumentInfo.anonymousAccessAllowed) &&
        Objects.equals(this.anonymousAllowsExport, btDocumentInfo.anonymousAllowsExport) &&
        Objects.equals(this.betaCapabilityIds, btDocumentInfo.betaCapabilityIds) &&
        Objects.equals(this.canMove, btDocumentInfo.canMove) &&
        Objects.equals(this.canUnshare, btDocumentInfo.canUnshare) &&
        Objects.equals(this.createdAt, btDocumentInfo.createdAt) &&
        Objects.equals(this.createdBy, btDocumentInfo.createdBy) &&
        Objects.equals(this.createdWithEducationPlan, btDocumentInfo.createdWithEducationPlan) &&
        Objects.equals(this.defaultElementId, btDocumentInfo.defaultElementId) &&
        Objects.equals(this.defaultWorkspace, btDocumentInfo.defaultWorkspace) &&
        Objects.equals(this.description, btDocumentInfo.description) &&
        Objects.equals(this.documentLabels, btDocumentInfo.documentLabels) &&
        Objects.equals(this.documentThumbnailElementId, btDocumentInfo.documentThumbnailElementId) &&
        Objects.equals(this.documentType, btDocumentInfo.documentType) &&
        Objects.equals(this.duplicateNameViolationError, btDocumentInfo.duplicateNameViolationError) &&
        Objects.equals(this.hasReleaseRevisionableObjects, btDocumentInfo.hasReleaseRevisionableObjects) &&
        Objects.equals(this.hasRelevantInsertables, btDocumentInfo.hasRelevantInsertables) &&
        Objects.equals(this.href, btDocumentInfo.href) &&
        Objects.equals(this.id, btDocumentInfo.id) &&
        Objects.equals(this.isContainer, btDocumentInfo.isContainer) &&
        Objects.equals(this.isEnterpriseOwned, btDocumentInfo.isEnterpriseOwned) &&
        Objects.equals(this.isMutable, btDocumentInfo.isMutable) &&
        Objects.equals(this.isOrphaned, btDocumentInfo.isOrphaned) &&
        Objects.equals(this.isUpgradedToLatestVersion, btDocumentInfo.isUpgradedToLatestVersion) &&
        Objects.equals(this.isUsingManagedWorkflow, btDocumentInfo.isUsingManagedWorkflow) &&
        Objects.equals(this.likedByCurrentUser, btDocumentInfo.likedByCurrentUser) &&
        Objects.equals(this.likes, btDocumentInfo.likes) &&
        Objects.equals(this.modifiedAt, btDocumentInfo.modifiedAt) &&
        Objects.equals(this.modifiedBy, btDocumentInfo.modifiedBy) &&
        Objects.equals(this.name, btDocumentInfo.name) &&
        Objects.equals(this.notRevisionManaged, btDocumentInfo.notRevisionManaged) &&
        Objects.equals(this.numberOfTimesCopied, btDocumentInfo.numberOfTimesCopied) &&
        Objects.equals(this.numberOfTimesReferenced, btDocumentInfo.numberOfTimesReferenced) &&
        Objects.equals(this.owner, btDocumentInfo.owner) &&
        Objects.equals(this.parentId, btDocumentInfo.parentId) &&
        Objects.equals(this.permission, btDocumentInfo.permission) &&
        Objects.equals(this.permissionSet, btDocumentInfo.permissionSet) &&
        Objects.equals(this.projectId, btDocumentInfo.projectId) &&
        Objects.equals(this._public, btDocumentInfo._public) &&
        Objects.equals(this.recentVersion, btDocumentInfo.recentVersion) &&
        Objects.equals(this.resourceType, btDocumentInfo.resourceType) &&
        Objects.equals(this.supportTeamUserAndShared, btDocumentInfo.supportTeamUserAndShared) &&
        Objects.equals(this.tags, btDocumentInfo.tags) &&
        Objects.equals(this.thumbnail, btDocumentInfo.thumbnail) &&
        Objects.equals(this.totalWorkspacesScheduledForUpdate, btDocumentInfo.totalWorkspacesScheduledForUpdate) &&
        Objects.equals(this.totalWorkspacesUpdating, btDocumentInfo.totalWorkspacesUpdating) &&
        Objects.equals(this.trash, btDocumentInfo.trash) &&
        Objects.equals(this.trashedAt, btDocumentInfo.trashedAt) &&
        Objects.equals(this.treeHref, btDocumentInfo.treeHref) &&
        Objects.equals(this.userAccountLimitsBreached, btDocumentInfo.userAccountLimitsBreached) &&
        Objects.equals(this.viewRef, btDocumentInfo.viewRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(anonymousAccessAllowed, anonymousAllowsExport, betaCapabilityIds, canMove, canUnshare, createdAt, createdBy, createdWithEducationPlan, defaultElementId, defaultWorkspace, description, documentLabels, documentThumbnailElementId, documentType, duplicateNameViolationError, hasReleaseRevisionableObjects, hasRelevantInsertables, href, id, isContainer, isEnterpriseOwned, isMutable, isOrphaned, isUpgradedToLatestVersion, isUsingManagedWorkflow, likedByCurrentUser, likes, modifiedAt, modifiedBy, name, notRevisionManaged, numberOfTimesCopied, numberOfTimesReferenced, owner, parentId, permission, permissionSet, projectId, _public, recentVersion, resourceType, supportTeamUserAndShared, tags, thumbnail, totalWorkspacesScheduledForUpdate, totalWorkspacesUpdating, trash, trashedAt, treeHref, userAccountLimitsBreached, viewRef);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTDocumentInfo {\n");
    sb.append("    anonymousAccessAllowed: ").append(toIndentedString(anonymousAccessAllowed)).append("\n");
    sb.append("    anonymousAllowsExport: ").append(toIndentedString(anonymousAllowsExport)).append("\n");
    sb.append("    betaCapabilityIds: ").append(toIndentedString(betaCapabilityIds)).append("\n");
    sb.append("    canMove: ").append(toIndentedString(canMove)).append("\n");
    sb.append("    canUnshare: ").append(toIndentedString(canUnshare)).append("\n");
    sb.append("    createdAt: ").append(toIndentedString(createdAt)).append("\n");
    sb.append("    createdBy: ").append(toIndentedString(createdBy)).append("\n");
    sb.append("    createdWithEducationPlan: ").append(toIndentedString(createdWithEducationPlan)).append("\n");
    sb.append("    defaultElementId: ").append(toIndentedString(defaultElementId)).append("\n");
    sb.append("    defaultWorkspace: ").append(toIndentedString(defaultWorkspace)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    documentLabels: ").append(toIndentedString(documentLabels)).append("\n");
    sb.append("    documentThumbnailElementId: ").append(toIndentedString(documentThumbnailElementId)).append("\n");
    sb.append("    documentType: ").append(toIndentedString(documentType)).append("\n");
    sb.append("    duplicateNameViolationError: ").append(toIndentedString(duplicateNameViolationError)).append("\n");
    sb.append("    hasReleaseRevisionableObjects: ").append(toIndentedString(hasReleaseRevisionableObjects)).append("\n");
    sb.append("    hasRelevantInsertables: ").append(toIndentedString(hasRelevantInsertables)).append("\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    isContainer: ").append(toIndentedString(isContainer)).append("\n");
    sb.append("    isEnterpriseOwned: ").append(toIndentedString(isEnterpriseOwned)).append("\n");
    sb.append("    isMutable: ").append(toIndentedString(isMutable)).append("\n");
    sb.append("    isOrphaned: ").append(toIndentedString(isOrphaned)).append("\n");
    sb.append("    isUpgradedToLatestVersion: ").append(toIndentedString(isUpgradedToLatestVersion)).append("\n");
    sb.append("    isUsingManagedWorkflow: ").append(toIndentedString(isUsingManagedWorkflow)).append("\n");
    sb.append("    likedByCurrentUser: ").append(toIndentedString(likedByCurrentUser)).append("\n");
    sb.append("    likes: ").append(toIndentedString(likes)).append("\n");
    sb.append("    modifiedAt: ").append(toIndentedString(modifiedAt)).append("\n");
    sb.append("    modifiedBy: ").append(toIndentedString(modifiedBy)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    notRevisionManaged: ").append(toIndentedString(notRevisionManaged)).append("\n");
    sb.append("    numberOfTimesCopied: ").append(toIndentedString(numberOfTimesCopied)).append("\n");
    sb.append("    numberOfTimesReferenced: ").append(toIndentedString(numberOfTimesReferenced)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    parentId: ").append(toIndentedString(parentId)).append("\n");
    sb.append("    permission: ").append(toIndentedString(permission)).append("\n");
    sb.append("    permissionSet: ").append(toIndentedString(permissionSet)).append("\n");
    sb.append("    projectId: ").append(toIndentedString(projectId)).append("\n");
    sb.append("    _public: ").append(toIndentedString(_public)).append("\n");
    sb.append("    recentVersion: ").append(toIndentedString(recentVersion)).append("\n");
    sb.append("    resourceType: ").append(toIndentedString(resourceType)).append("\n");
    sb.append("    supportTeamUserAndShared: ").append(toIndentedString(supportTeamUserAndShared)).append("\n");
    sb.append("    tags: ").append(toIndentedString(tags)).append("\n");
    sb.append("    thumbnail: ").append(toIndentedString(thumbnail)).append("\n");
    sb.append("    totalWorkspacesScheduledForUpdate: ").append(toIndentedString(totalWorkspacesScheduledForUpdate)).append("\n");
    sb.append("    totalWorkspacesUpdating: ").append(toIndentedString(totalWorkspacesUpdating)).append("\n");
    sb.append("    trash: ").append(toIndentedString(trash)).append("\n");
    sb.append("    trashedAt: ").append(toIndentedString(trashedAt)).append("\n");
    sb.append("    treeHref: ").append(toIndentedString(treeHref)).append("\n");
    sb.append("    userAccountLimitsBreached: ").append(toIndentedString(userAccountLimitsBreached)).append("\n");
    sb.append("    viewRef: ").append(toIndentedString(viewRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

