/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BTDocumentProcessingInfoAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTDocumentProcessingInfoAllOf {
  public static final String SERIALIZED_NAME_TRANSLATION_EVENT_KEY = "translationEventKey";
  @SerializedName(SERIALIZED_NAME_TRANSLATION_EVENT_KEY)
  private String translationEventKey;

  public static final String SERIALIZED_NAME_TRANSLATION_ID = "translationId";
  @SerializedName(SERIALIZED_NAME_TRANSLATION_ID)
  private String translationId;

  public BTDocumentProcessingInfoAllOf() { 
  }

  public BTDocumentProcessingInfoAllOf translationEventKey(String translationEventKey) {
    
    this.translationEventKey = translationEventKey;
    return this;
  }

   /**
   * Get translationEventKey
   * @return translationEventKey
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTranslationEventKey() {
    return translationEventKey;
  }


  public void setTranslationEventKey(String translationEventKey) {
    this.translationEventKey = translationEventKey;
  }


  public BTDocumentProcessingInfoAllOf translationId(String translationId) {
    
    this.translationId = translationId;
    return this;
  }

   /**
   * Get translationId
   * @return translationId
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTranslationId() {
    return translationId;
  }


  public void setTranslationId(String translationId) {
    this.translationId = translationId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTDocumentProcessingInfoAllOf btDocumentProcessingInfoAllOf = (BTDocumentProcessingInfoAllOf) o;
    return Objects.equals(this.translationEventKey, btDocumentProcessingInfoAllOf.translationEventKey) &&
        Objects.equals(this.translationId, btDocumentProcessingInfoAllOf.translationId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(translationEventKey, translationId);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTDocumentProcessingInfoAllOf {\n");
    sb.append("    translationEventKey: ").append(toIndentedString(translationEventKey)).append("\n");
    sb.append("    translationId: ").append(toIndentedString(translationId)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

