/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.client.model.BTThumbnailSizeInfo;

/**
 * BTThumbnailInfo
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTThumbnailInfo {
  public static final String SERIALIZED_NAME_HREF = "href";
  @SerializedName(SERIALIZED_NAME_HREF)
  private URI href;

  public static final String SERIALIZED_NAME_ID = "id";
  @SerializedName(SERIALIZED_NAME_ID)
  private String id;

  public static final String SERIALIZED_NAME_SECONDARY_SIZES = "secondarySizes";
  @SerializedName(SERIALIZED_NAME_SECONDARY_SIZES)
  private List<List<BTThumbnailSizeInfo>> secondarySizes = null;

  public static final String SERIALIZED_NAME_SIZES = "sizes";
  @SerializedName(SERIALIZED_NAME_SIZES)
  private List<BTThumbnailSizeInfo> sizes = null;

  public BTThumbnailInfo() { 
  }

  public BTThumbnailInfo href(URI href) {
    
    this.href = href;
    return this;
  }

   /**
   * Get href
   * @return href
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public URI getHref() {
    return href;
  }


  public void setHref(URI href) {
    this.href = href;
  }


  public BTThumbnailInfo id(String id) {
    
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getId() {
    return id;
  }


  public void setId(String id) {
    this.id = id;
  }


  public BTThumbnailInfo secondarySizes(List<List<BTThumbnailSizeInfo>> secondarySizes) {
    
    this.secondarySizes = secondarySizes;
    return this;
  }

  public BTThumbnailInfo addSecondarySizesItem(List<BTThumbnailSizeInfo> secondarySizesItem) {
    if (this.secondarySizes == null) {
      this.secondarySizes = new ArrayList<List<BTThumbnailSizeInfo>>();
    }
    this.secondarySizes.add(secondarySizesItem);
    return this;
  }

   /**
   * Get secondarySizes
   * @return secondarySizes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<List<BTThumbnailSizeInfo>> getSecondarySizes() {
    return secondarySizes;
  }


  public void setSecondarySizes(List<List<BTThumbnailSizeInfo>> secondarySizes) {
    this.secondarySizes = secondarySizes;
  }


  public BTThumbnailInfo sizes(List<BTThumbnailSizeInfo> sizes) {
    
    this.sizes = sizes;
    return this;
  }

  public BTThumbnailInfo addSizesItem(BTThumbnailSizeInfo sizesItem) {
    if (this.sizes == null) {
      this.sizes = new ArrayList<BTThumbnailSizeInfo>();
    }
    this.sizes.add(sizesItem);
    return this;
  }

   /**
   * Get sizes
   * @return sizes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<BTThumbnailSizeInfo> getSizes() {
    return sizes;
  }


  public void setSizes(List<BTThumbnailSizeInfo> sizes) {
    this.sizes = sizes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTThumbnailInfo btThumbnailInfo = (BTThumbnailInfo) o;
    return Objects.equals(this.href, btThumbnailInfo.href) &&
        Objects.equals(this.id, btThumbnailInfo.id) &&
        Objects.equals(this.secondarySizes, btThumbnailInfo.secondarySizes) &&
        Objects.equals(this.sizes, btThumbnailInfo.sizes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(href, id, secondarySizes, sizes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTThumbnailInfo {\n");
    sb.append("    href: ").append(toIndentedString(href)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    secondarySizes: ").append(toIndentedString(secondarySizes)).append("\n");
    sb.append("    sizes: ").append(toIndentedString(sizes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

