/*
 * Onshape REST API
 * The Onshape REST API consumed by all client. # Authorization The simplest way to authorize and enable the **Try it out** functionality is to sign in to Onshape and use the current session. The **Authorize** button enables other authorization techniques. To ensure the current session isn't used when trying other authentication techniques, make sure to remove the Onshape cookie as per the instructions for your particular browser. Alternatively, a private or incognito window may be used. Here's [how to remove a specific cookie on Chrome](https://support.google.com/chrome/answer/95647#zippy=%2Cdelete-cookies-from-a-site). - **Current Session** authorization is enabled by default if the browser is already signed in to [Onshape](/). - **OAuth2** authorization uses an Onshape OAuth2 app created on the [Onshape Developer Portal](https://dev-portal.onshape.com/oauthApps). The redirect URL field should include `https://cad.onshape.com/glassworks/explorer/oauth2-redirect.html`. - **API Key** authorization using basic authentication is also available. The keys can be generated in the [Onshape Developer Portal](https://dev-portal.onshape.com/keys). In the authentication dialog, enter the access key in the `Username` field, and enter the secret key in the `Password` field. Basic authentication should only be used during the development process since sharing API Keys provides the same level of access as a username and password.
 *
 * The version of the OpenAPI document: 1.147.4893-d7846311aebf
 * Contact: api-support@onshape.zendesk.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.openapitools.client.model.BTCompanySummaryInfo;
import org.openapitools.client.model.GlobalPermissionInfo;
import org.threeten.bp.OffsetDateTime;

/**
 * BTUserSummaryInfoAllOf
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-05-18T10:48:36.222032-04:00[America/New_York]")
public class BTUserSummaryInfoAllOf {
  public static final String SERIALIZED_NAME_COMPANY = "company";
  @SerializedName(SERIALIZED_NAME_COMPANY)
  private BTCompanySummaryInfo company;

  public static final String SERIALIZED_NAME_DOCUMENTATION_NAME = "documentationName";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION_NAME)
  private String documentationName;

  public static final String SERIALIZED_NAME_DOCUMENTATION_NAME_OVERRIDE = "documentationNameOverride";
  @SerializedName(SERIALIZED_NAME_DOCUMENTATION_NAME_OVERRIDE)
  private String documentationNameOverride;

  public static final String SERIALIZED_NAME_EMAIL = "email";
  @SerializedName(SERIALIZED_NAME_EMAIL)
  private String email;

  public static final String SERIALIZED_NAME_FIRST_NAME = "firstName";
  @SerializedName(SERIALIZED_NAME_FIRST_NAME)
  private String firstName;

  public static final String SERIALIZED_NAME_GLOBAL_PERMISSIONS = "globalPermissions";
  @SerializedName(SERIALIZED_NAME_GLOBAL_PERMISSIONS)
  private GlobalPermissionInfo globalPermissions;

  public static final String SERIALIZED_NAME_IS_GUEST = "isGuest";
  @SerializedName(SERIALIZED_NAME_IS_GUEST)
  private Boolean isGuest;

  public static final String SERIALIZED_NAME_IS_LIGHT = "isLight";
  @SerializedName(SERIALIZED_NAME_IS_LIGHT)
  private Boolean isLight;

  public static final String SERIALIZED_NAME_LAST_LOGIN_TIME = "lastLoginTime";
  @SerializedName(SERIALIZED_NAME_LAST_LOGIN_TIME)
  private OffsetDateTime lastLoginTime;

  public static final String SERIALIZED_NAME_LAST_NAME = "lastName";
  @SerializedName(SERIALIZED_NAME_LAST_NAME)
  private String lastName;

  public static final String SERIALIZED_NAME_PERSONAL_MESSAGE_ALLOWED = "personalMessageAllowed";
  @SerializedName(SERIALIZED_NAME_PERSONAL_MESSAGE_ALLOWED)
  private Boolean personalMessageAllowed;

  public static final String SERIALIZED_NAME_SOURCE = "source";
  @SerializedName(SERIALIZED_NAME_SOURCE)
  private Integer source;

  public BTUserSummaryInfoAllOf() { 
  }

  public BTUserSummaryInfoAllOf company(BTCompanySummaryInfo company) {
    
    this.company = company;
    return this;
  }

   /**
   * Get company
   * @return company
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public BTCompanySummaryInfo getCompany() {
    return company;
  }


  public void setCompany(BTCompanySummaryInfo company) {
    this.company = company;
  }


  public BTUserSummaryInfoAllOf documentationName(String documentationName) {
    
    this.documentationName = documentationName;
    return this;
  }

   /**
   * Get documentationName
   * @return documentationName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDocumentationName() {
    return documentationName;
  }


  public void setDocumentationName(String documentationName) {
    this.documentationName = documentationName;
  }


  public BTUserSummaryInfoAllOf documentationNameOverride(String documentationNameOverride) {
    
    this.documentationNameOverride = documentationNameOverride;
    return this;
  }

   /**
   * Get documentationNameOverride
   * @return documentationNameOverride
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getDocumentationNameOverride() {
    return documentationNameOverride;
  }


  public void setDocumentationNameOverride(String documentationNameOverride) {
    this.documentationNameOverride = documentationNameOverride;
  }


  public BTUserSummaryInfoAllOf email(String email) {
    
    this.email = email;
    return this;
  }

   /**
   * Get email
   * @return email
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getEmail() {
    return email;
  }


  public void setEmail(String email) {
    this.email = email;
  }


  public BTUserSummaryInfoAllOf firstName(String firstName) {
    
    this.firstName = firstName;
    return this;
  }

   /**
   * Get firstName
   * @return firstName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getFirstName() {
    return firstName;
  }


  public void setFirstName(String firstName) {
    this.firstName = firstName;
  }


  public BTUserSummaryInfoAllOf globalPermissions(GlobalPermissionInfo globalPermissions) {
    
    this.globalPermissions = globalPermissions;
    return this;
  }

   /**
   * Get globalPermissions
   * @return globalPermissions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public GlobalPermissionInfo getGlobalPermissions() {
    return globalPermissions;
  }


  public void setGlobalPermissions(GlobalPermissionInfo globalPermissions) {
    this.globalPermissions = globalPermissions;
  }


  public BTUserSummaryInfoAllOf isGuest(Boolean isGuest) {
    
    this.isGuest = isGuest;
    return this;
  }

   /**
   * Get isGuest
   * @return isGuest
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsGuest() {
    return isGuest;
  }


  public void setIsGuest(Boolean isGuest) {
    this.isGuest = isGuest;
  }


  public BTUserSummaryInfoAllOf isLight(Boolean isLight) {
    
    this.isLight = isLight;
    return this;
  }

   /**
   * Get isLight
   * @return isLight
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getIsLight() {
    return isLight;
  }


  public void setIsLight(Boolean isLight) {
    this.isLight = isLight;
  }


  public BTUserSummaryInfoAllOf lastLoginTime(OffsetDateTime lastLoginTime) {
    
    this.lastLoginTime = lastLoginTime;
    return this;
  }

   /**
   * Get lastLoginTime
   * @return lastLoginTime
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public OffsetDateTime getLastLoginTime() {
    return lastLoginTime;
  }


  public void setLastLoginTime(OffsetDateTime lastLoginTime) {
    this.lastLoginTime = lastLoginTime;
  }


  public BTUserSummaryInfoAllOf lastName(String lastName) {
    
    this.lastName = lastName;
    return this;
  }

   /**
   * Get lastName
   * @return lastName
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLastName() {
    return lastName;
  }


  public void setLastName(String lastName) {
    this.lastName = lastName;
  }


  public BTUserSummaryInfoAllOf personalMessageAllowed(Boolean personalMessageAllowed) {
    
    this.personalMessageAllowed = personalMessageAllowed;
    return this;
  }

   /**
   * Get personalMessageAllowed
   * @return personalMessageAllowed
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPersonalMessageAllowed() {
    return personalMessageAllowed;
  }


  public void setPersonalMessageAllowed(Boolean personalMessageAllowed) {
    this.personalMessageAllowed = personalMessageAllowed;
  }


  public BTUserSummaryInfoAllOf source(Integer source) {
    
    this.source = source;
    return this;
  }

   /**
   * Get source
   * @return source
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getSource() {
    return source;
  }


  public void setSource(Integer source) {
    this.source = source;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BTUserSummaryInfoAllOf btUserSummaryInfoAllOf = (BTUserSummaryInfoAllOf) o;
    return Objects.equals(this.company, btUserSummaryInfoAllOf.company) &&
        Objects.equals(this.documentationName, btUserSummaryInfoAllOf.documentationName) &&
        Objects.equals(this.documentationNameOverride, btUserSummaryInfoAllOf.documentationNameOverride) &&
        Objects.equals(this.email, btUserSummaryInfoAllOf.email) &&
        Objects.equals(this.firstName, btUserSummaryInfoAllOf.firstName) &&
        Objects.equals(this.globalPermissions, btUserSummaryInfoAllOf.globalPermissions) &&
        Objects.equals(this.isGuest, btUserSummaryInfoAllOf.isGuest) &&
        Objects.equals(this.isLight, btUserSummaryInfoAllOf.isLight) &&
        Objects.equals(this.lastLoginTime, btUserSummaryInfoAllOf.lastLoginTime) &&
        Objects.equals(this.lastName, btUserSummaryInfoAllOf.lastName) &&
        Objects.equals(this.personalMessageAllowed, btUserSummaryInfoAllOf.personalMessageAllowed) &&
        Objects.equals(this.source, btUserSummaryInfoAllOf.source);
  }

  @Override
  public int hashCode() {
    return Objects.hash(company, documentationName, documentationNameOverride, email, firstName, globalPermissions, isGuest, isLight, lastLoginTime, lastName, personalMessageAllowed, source);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BTUserSummaryInfoAllOf {\n");
    sb.append("    company: ").append(toIndentedString(company)).append("\n");
    sb.append("    documentationName: ").append(toIndentedString(documentationName)).append("\n");
    sb.append("    documentationNameOverride: ").append(toIndentedString(documentationNameOverride)).append("\n");
    sb.append("    email: ").append(toIndentedString(email)).append("\n");
    sb.append("    firstName: ").append(toIndentedString(firstName)).append("\n");
    sb.append("    globalPermissions: ").append(toIndentedString(globalPermissions)).append("\n");
    sb.append("    isGuest: ").append(toIndentedString(isGuest)).append("\n");
    sb.append("    isLight: ").append(toIndentedString(isLight)).append("\n");
    sb.append("    lastLoginTime: ").append(toIndentedString(lastLoginTime)).append("\n");
    sb.append("    lastName: ").append(toIndentedString(lastName)).append("\n");
    sb.append("    personalMessageAllowed: ").append(toIndentedString(personalMessageAllowed)).append("\n");
    sb.append("    source: ").append(toIndentedString(source)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

